# Generated by Django 3.2.9 on 2021-11-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techit', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand')),
                ('hover_image', models.ImageField(upload_to='brand')),
            ],
        ),
    ]
