# Generated by Django 3.2.9 on 2021-11-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techit', '0010_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
